spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chamedu-mysql.ckoldtvydv7j.ap-northeast-2.rds.amazonaws.com:3306/chamdb
    username: admin
    password: chamedu23

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        format_sql: true


#logging:
#  level:
#    com.tutorial: debug
#jwt:
#  secret: "VlwEyVBsYt9V7zq57TejMnVUyzblYcffUjXn2opi2990s90sd0sdk283l5u8x"

