spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chamedu-mysql.ckoldtvydv7j.ap-northeast-2.rds.amazonaws.com:3306/chamdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: chamedu23


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true


logging:
  level:
    com.example: debug
jwt:
  secret: chamedu.is.the.best.educationapp
# VlwEyVBsYt9V7zq57TejMnVUyzblYcffUjXn2opi2990s90sd0sdk283l5u8x

